### ISSUE TITLE
Please release nuget package

### ISSUE THREAD

**Issue by toburger** [fsprojects/FSharpx.Async#37]
### Description

Please update the nuget package with fixed ParallelWithThrottle (https://github.com/fsprojects/FSharpx.Async/pull/35)

### Known workarounds

Use paket with single file github reference

```
github fsprojects/FSharpx.Async src/FSharpx.Async/Agent.fs
github fsprojects/FSharpx.Async src/FSharpx.Async/Async.fs
```

**Comment by forki** [comment]
@toburger @tpetricek I've released it.
